version: '3.2'

networks:
  healthify_net:
    external: true

volumes:
  pgdata:

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthify
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - healthify_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
      labels:
        - "monitoring=true"

  backend:
    image: ${REGISTRY}/healthify-backend:${VERSION}
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    networks:
      - healthify_net
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "monitoring=true"

  frontend:
    image: ${REGISTRY}/healthify-frontend:${VERSION}
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    networks:
      - healthify_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "monitoring=true"
