---
- name: Deploy monitoring stack (Prometheus, Grafana, Blackbox)
  hosts: swarm_manager
  become: yes
  vars:
    monitor_dir: /home/jenkins/monitoring
    stack_file: "{{ monitor_dir }}/monitoring-stack.yml"
    prometheus_config: "{{ monitor_dir }}/prometheus.yml"
    alert_rules: "{{ monitor_dir }}/alert.rules.yml"
    grafana_data_dir: /var/lib/grafana
    overlay_network: monitoring_net

  tasks:
    - name: Ensure monitoring directory exists
      ansible.builtin.file:
        path: "{{ monitor_dir }}"
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
        recurse: yes
      tags: [monitoring]

    - name: Ensure overlay network exists
      ansible.builtin.shell: |
        docker network inspect {{ overlay_network }} >/dev/null 2>&1 || \
        docker network create --driver overlay --attachable {{ overlay_network }}
      args:
        warn: false
      tags: [monitoring]

    - name: Copy monitoring stack file
      ansible.builtin.copy:
        src: files/monitoring-stack.yml
        dest: "{{ stack_file }}"
        owner: jenkins
        group: jenkins
        mode: '0644'
      tags: [monitoring]

    - name: Copy Prometheus config
      ansible.builtin.copy:
        src: files/prometheus.yml
        dest: "{{ prometheus_config }}"
        owner: jenkins
        group: jenkins
        mode: '0644'
      tags: [monitoring]

    - name: Copy alert rules
      ansible.builtin.copy:
        src: files/alert.rules.yml
        dest: "{{ alert_rules }}"
        owner: jenkins
        group: jenkins
        mode: '0644'
      tags: [monitoring]

    - name: Ensure Grafana data directory exists
      ansible.builtin.file:
        path: "{{ grafana_data_dir }}"
        state: directory
        owner: 472
        group: 472
        mode: '0755'
      tags: [monitoring]

    - name: Check Docker is running
      ansible.builtin.shell: docker info
      register: docker_info
      changed_when: false
      failed_when: docker_info.rc != 0
      tags: [monitoring]

    - name: Deploy monitoring stack
      ansible.builtin.shell: |
        docker stack deploy -c {{ stack_file }} monitoring --prune
      tags: [monitoring]
